# Generated by Django 4.0.1 on 2022-01-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
