# Generated by Django 4.0.1 on 2022-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person_age_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='SN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(default='autre', max_length=255),
            preserve_default=False,
        ),
    ]
